import { RegistrationStatus as S } from '../enums/registration.js';
import { defineStateMachine } from './machine.js';

/**
 * handoff 7.2:
 * DRAFT → WAITING_MEMBERS → WAITING_PAYMENT → CONFIRMED → CHECKED_IN → FINISHED
 * Альтернативы: WAITLISTED, PAYMENT_FAILED, CANCELLED, REFUND_PENDING, REFUNDED, REJECTED.
 */
export const registrationMachine = defineStateMachine<S>('Registration', S.DRAFT, {
  DRAFT: [S.WAITING_MEMBERS, S.WAITING_PAYMENT, S.WAITLISTED, S.CANCELLED],
  WAITING_MEMBERS: [S.WAITING_PAYMENT, S.CANCELLED, S.REJECTED],
  WAITING_PAYMENT: [S.CONFIRMED, S.PAYMENT_FAILED, S.CANCELLED, S.REJECTED],
  PAYMENT_FAILED: [S.WAITING_PAYMENT, S.CANCELLED],
  WAITLISTED: [S.WAITING_MEMBERS, S.WAITING_PAYMENT, S.CANCELLED, S.REJECTED],
  CONFIRMED: [S.CHECKED_IN, S.REFUND_PENDING, S.CANCELLED, S.REJECTED],
  CHECKED_IN: [S.FINISHED],
  FINISHED: [],
  CANCELLED: [S.REFUND_PENDING],
  REFUND_PENDING: [S.REFUNDED],
  REFUNDED: [],
  REJECTED: [S.REFUND_PENDING],
});
